TrabajoFinalBuzzi/TiendaYaguarete/Tienda/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
    path('acerca/', views.acerca, name="acerca"),
    path('filtro_categoria/<int:categoria_id>', views.filtro_categoria, name="filtro_categoria"),
    path('mostrar_producto/<int:producto_id>', views.mostrar_producto, name="mostrar_producto"),
    path('buscar_producto/<str:descripcion_prod>', views.buscar_producto, name="buscar_producto"),
    path('contacto/', views.contacto, name="contacto"),
    path('carrito/', views.carrito, name="carrito"),
    path('nuevo_producto/', views.nuevo_producto, name="nuevo_producto"),
    path('edicion_producto/<int:producto_id>', views.edicion_producto, name="edicion_producto"),
    path('eliminar_producto_bd/<int:producto_id>', views.eliminar_producto_bd, name="eliminar_producto_bd"),  
 
    
    # Para el carrito
    path("agregar/<int:producto_id>", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),


    #path('saludar/<str:nombre>', views.hola, name="hola"),
    #path('plantilla', views.plantilla, name="plantilla"),
    #path('plantillasaludo/<str:nombre>', views.saludar, name="saludar"),

]

TrabajoFinalBuzzi/TiendaYaguarete/TiendaYaguarete/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Tienda.urls")),
    path('tienda/', include("Tienda.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/login/', include('TiendaYaguarete.urls')),
    path('registrarse/', include('USUARIOS.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrabajoFinalBuzzi/TiendaYaguarete/USUARIOS/urls.py
from django.urls import path, include
from . import views

app_name = "USUARIOS"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return self.descripcion

class Producto(models.Model):

    titulo = models.CharField(max_length=45, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    descripcion= models.CharField(max_length=250, null=False)
    categoria= models.ForeignKey(Categoria, on_delete=models.CASCADE,null=False, related_name="categoriaproducto")
    precio= models.FloatField(default=0.00, null=False) 
   
#   precio= models.FloatField(max_digits=10, decimal_places=2, default=0, null=False) 
    def __str__(self):
         return f"{self.titulo} - {self.descripcion} - {self.precio} ({self.categoria})"

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    productos= models.ManyToManyField(Producto)
    total= models.DecimalField(max_digits=10 , decimal_places=2, default=0) 

    def __str__(self):
        return f"{self.usuario} - {self.total}"

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/forms.py
from django import forms
from .models import Producto

class FormProducto(forms.ModelForm):

    #campos del modelo
    class Meta:
        model = Producto
        fields = ('titulo','imagen', 'descripcion','categoria','precio')
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
            'categoria': forms.Select(attrs={'class': 'pub_categoria'}),
            'descripcion':forms.Textarea(attrs={'class': 'pub_categoria'}),
            'precio': forms.TextInput(attrs={'class': 'pub_precio'}),
           
        }

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils.regex_helper import contains
from .forms import *
from .models import Carrito, Categoria,Producto
from django.http import HttpResponse
from .carro import Carro
from django.db.models import Q



# Create your views here.


def index(request):  

    try:
        registros=Producto.objects.count();
        registros_ultimos=registros-3;
        registros_anteriores=registros-10;
   
        return render(request,"tienda/index.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all(),
        #"primeros_productos" : Producto.objects.raw('SELECT * FROM Productos order by id DESC LIMIT 3'),
       "primeros_productos" : Producto.objects.all()[registros_ultimos:],
        "ultimos_productos": Producto.objects.all()[registros_anteriores:registros_ultimos],

        })
    except:
        return render(request,"tienda/index.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all()
        })

def acerca(request):
        return render(request,"tienda/acerca.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all(),
    })


def filtro_categoria(request,categoria_id):
    una_categoria = get_object_or_404(Categoria, id=categoria_id)
    queryset = Producto.objects.all()
    queryset = queryset.filter(categoria=una_categoria)
    #return HttpResponse(una_categoria.des)
    return render(request,"tienda/filtro_categoria.html",{"lista_categorias":Categoria.objects.all(), 
    "categoria_seleccionada":una_categoria, "lista_productos":queryset})



def buscar_producto(request,descripcion_prod):
    #items =  get_object_or_404(Producto, descripcion__contains=descripcion_prod)
    items = Producto.objects.filter(Q(descripcion__contains=descripcion_prod)|Q(titulo__contains=descripcion_prod))
    queryset = Producto.objects.all(),
    #return HttpResponse(una_categoria.des)
    return render(request,"tienda/buscar_producto.html",{"lista_categorias":Categoria.objects.all(), 
    "lista_productos":queryset, 
    "items_encontrados":items,"buscado":descripcion_prod})
 

   
def contacto(request):
        return render(request,"tienda/contacto.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all(),
    })

def carrito(request):
        return render(request,"tienda/carrito.html")

"""return render(request,"tienda/carrito.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all(),"""
    
    

def nuevo_producto(request):  
    if request.method == "POST":
        

        #cat = Categoria.objects.get(id=1)
        #form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=cat)) 
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'])) 
        if form.is_valid():
            form.save()
        return redirect("/")    
        """return render(request,"tienda/index.html", {
        "lista_productos": Producto.objects.all(),
        "lista_categorias": Categoria.objects.all()
        })"""
        #return render (request,"tienda/index.html") 
         #return render (request,"Tienda/index.html")          
    else:
        form = FormProducto()
    return render(request, "tienda/nuevo_producto.html", {
            "form": form, "lista_productos": Producto.objects.all(),
            "lista_categorias": Categoria.objects.all()
     })
def edicion_producto (request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":  
        form = FormProducto(data=request.POST, files=request.FILES, instance=un_producto)
        if form.is_valid():
            form.save()
        return redirect("/")   
       
    else:
        form = FormProducto(instance = un_producto)
    return render(request, 'tienda/edicion_producto.html', {
            "un_producto": un_producto,
            "form": form
        })
  
""""def edicion_producto(request,producto_id):
   un_producto = get_object_or_404(Producto, id=producto_id)
   form = FormProducto(request.POST or None, request.FILES, instance=un_producto)  
   if form.is_valid():
        form.save()
        #messages.success(request,"SE edito correctamente") 
   return render(request,"tienda/edicion_producto.html", {
            "form":form ,"id":un_producto
   })
 
    
def articulo_editar(request, articulo_id):
    un_articulo = get_object_or_404(Articulo, id=articulo_id)
    if request.method == "POST":  
        user = User.objects.get(username=request.user)   
        un_articulo.publicador = user
        form = FormArticulo(data=request.POST, files=request.FILES, instance=un_articulo)
        if form.is_valid():
            form.save()
            return redirect("sitio:index")
    else:
        form = FormArticulo(instance = un_articulo)
        return render(request, 'blog/articulo_edicion.html', {
            "articulo": un_articulo,
            "form": form
        })"""

def eliminar_producto_bd(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    un_producto.delete()
    #return render(request,"tienda/index.html")
    return redirect("index")
     

def mostrar_producto(request,producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    queryset = Producto.objects.all()
    una_categoria=un_producto.categoria
    #queryset = queryset.filter(id=un_producto)
    #return HttpResponse(una_categoria.des)
    return render(request,"tienda/mostrar_producto.html",{"lista_categorias":Categoria.objects.all(), 
    "producto_seleccionado":un_producto,"categoria_seleccionada":una_categoria, "lista_productos":queryset})        



# para el carrito
def agregar_producto(request, producto_id):
    
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("/carrito")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("/carrito")


def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("/carrito")


def limpiar_carro(request):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("/carrito")

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/acerca.html
{% extends "tienda/layout.html" %}

       
{% block content %}

<h4 class="text-center">Acerca de la empresa</h4>
<jumbotron class="fixed-canter" >
<p></p>
<h5 class="text-success">Yaguarete S.A tiene sus orígenes en el año 2.000 , cuando un grupo de amigos se asoció para emprender. </h5>
<p></p>
<h5 class="text-success">Nuestra misión se basa en brindar la mejor atencion a nuestros clientes, brindando los  productos de la mejor calidad </h5>
<p></p>
</jumbotron>
{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/buscar_producto.html
{% extends "tienda/layout.html" %}

       
{% block content %}

{%if buscado%}
<h5 class="text-center">Coincidencias para: {{buscado}}</h5>

{% for it  in items_encontrados %}
<ul class="list-group-xs" padding="10px 10px 10px 10px">
   <li class="list-group-item list-group-item">  
   {%if not request.user.is_superuser%}            
     <a href="{% url 'mostrar_producto' it.id%}"<h6>{{it.titulo}}  --    {{it.descripcion}}</h6>
   {%else%}
   <a href="{% url 'edicion_producto' it.id%}"<h6>{{it.titulo}}  --    {{it.descripcion}}</h6> 
   {%endif%} 
</li>
</ul>
{%empty%}
<h4 class="text-center">No se encontraron resultados para la busqueda efectuada</h4>
{%endfor%}


{%else%}
<h5 class="text-center">No ingresó nada a buscar</h5>
{%endif%}
{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/carrito.html
{% extends "tienda/layout.html" %}

       
{% block content %}
{% if request.user.is_authenticated%}
{%if not request.user.is_superuser%}
<h4 class="text-center">Carrito de compra del usuario: {{request.user}}</h4>
<div class="table-responsive" width="80%">
    <table class="table table-striped bg-light">
                <thead>
                    <th class="text-center" style="width: 25%";>Producto</th>
    
                    <th class="text-center">Precio</th>
                    <th style="width: 28%">Cantidad</th>
                
                </thead>
                <tbody>
                    {% if request.session.carro.items %}
            
                    {% for key, value in request.session.carro.items %}
              
                          
                      <input type="hidden" type="text" name="iditem" id="iditem" 
                      value={{value.id}}>
                        <tr>
                            <td class="text-center">{{value.titulo}}
                          </td>
                          <td class="text-center"><input type="number" name="precio"
                            id="precio" value={{value.precio}}  style="width: 25%"   readonly="true">
                            
                            <br/>
                           </td>
                           <td class="text-center"><input type="number" name="cantidad" id="cantidad" style="width: 15%" 
                            min="0" max="500" size="3" value={{value.cantidad}} readonly="true">
                            <a href="{% url 'agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                            <a href="{% url 'restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                            <a href="{% url 'eliminar' value.producto_id %}" class="btn btn-sm btn-danger">Quitar producto</a> 
                           </td>
   
                         
              

                        </tr>
           
                    {%endfor%}
                {%else%}
                <tr>

                    <td colspan="3">
                        <div class="alert alert-danger text-center">
    
                            El carro no tiene productos cargados
                        </div>
    
                    </td>
    
                </tr>
            {% endif %} 
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3">
            
                            <h4 class="text-center border">Total $: {{importe_total_carro}} </h4>
                            <p></p>
                            <a href="{% url 'limpiar'%}" class="btn btn-sm btn-success">Vaciar carrito</a> 
                            <a href="" class="btn btn-sm btn-success" onclick="saludar()">Enviar carrito</a> 
                        </td>
                          
            
            
                    </tr>
                </tfoot>     
    </table>

</div>
{%else%}
<h4>No tiene permiso para ver el carrito</h4>
{%endif%}
{%else%}
<h5>Para llenar el carrito debe conectarse como usuario normal</h5>
{%endif%}
{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/contacto.html
{% extends "tienda/layout.html" %}

       
{% block content %}

        <h5 align="center">Datos de contacto</h5>
<p></p>
<h4>Nos encontramos en pleno Centro de Cordoba en la Calle Ssn jeronimo 500, no dudes en
        contactarte con nosotros para efectuar cualquier consulta.Contáctanos en nuestra dirección de <a href="mailto:contacto@yaguarete.com">email</a></h4>
  
{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/edicion_producto.html
{% extends "tienda/layout.html" %}
{% block content %}
<div="container">
    <div class="shadow-lg">       
 {%if request.user.is_superuser%}       
<h3>Edición -Borrado de producto</h3>
<form  enctype="multipart/form-data" action="{%url 'edicion_producto' un_producto.id%}" method="post" >
    {% csrf_token %}
    <div class="form-group row text-center">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label>
        {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label>
        {{form.imagen}} {{ form.imagen.errors}}
    </div>
    <div class="form-group row">
        <label for="categoria_input"  class="col-sm-2 col-form-label">Categoria</label> 
        {{ form.categoria}} {{ form.categoria.errors }}
    </div>
    <div class="form-group row">
        <label for="descripcion_textArea"  class="col-sm-2 col-form-label">Descripcion</label> 
        {{ form.descripcion }} {{ form.descripcion.errors }}
    </div>


 
    <div class="form-group row">
        <label for="precio_input"  class="col-sm-2 col-form-label">Precio $</label> 
        {{ form.precio }} {{ form.precio.errors }}
    </div>  
    <!--<div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label><br> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>-->
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" type="button" href="{% url 'index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
        <a class="btn btn-danger  " href="{%url 'eliminar_producto_bd' un_producto.id%}">Eliminar</a>
    </div>
    
</form>

{%else%}
 <h4>No tiene permisos para dar de alta productos</h4>
{%endif%}
</div>
</div>
{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/filtro_categoria.html
{% extends "tienda/layout.html" %}

       
{% block content %}
{% if lista_productos%}
 
<h5 align="center">Categoria buscada - {{categoria_seleccionada.descripcion}}</h5>

{% for producto in lista_productos %}
<ul class="list-group-xs" padding="20px 30px 20px 10px">
<li class="list-group-item list-group-item-secondary">
   {%if not request.user.is_superuser%}           
     <a href="{% url 'mostrar_producto' producto.id%}"><h6>{{producto.titulo}}  -  {{producto.descripcion}}</h6></a>
   {%else%}
     <a href="{% url 'edicion_producto' producto.id%}"><h6>{{producto.titulo}}  -  {{producto.descripcion}}</h6></a>
   {%endif%}
</li>
</ul>
{% empty %}
<h5 class="text-center">No hay productos en la categoria seleccionada</h5>
{% endfor %}
{%else%}
<h5 class="text-center">No hay productos en la categoria seleccionada</h5>
{%endif%}




{% endblock %}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/index.html
{% extends "tienda/layout.html" %}

{% block content%} 
<div="container">
    <div class="shadow-lg">
        <p></p>
        <h5 align="center">Ultimos productos agregados</h5>

       
        <div class="row" style="padding:10px 10px 10px 10px">
            {% for primero in primeros_productos %}  

            <div class="col-4">
     

                <div class="card" style="padding:10px 10px 10px 10px">
              

                    <div class="card-body text-center" name="tarjeta" id="">

                        <class="card-text"><label class="text-center"><h5>{{primero.titulo}}</h5></label>
    
                        <p></p>
                        <class="card-text"><label class="text-center"><img src="{{primero.imagen.url}}" width="200px" height="200px"></label>
                        <p></p>
                       
                        {%if not request.user.is_superuser%}
                        <class="card-text"><a class="btn btn-md btn-success text-center" href="{% url 'mostrar_producto' primero.id%}">Ver</a>
                            <p></p>
                        {%else%}
                        <class="card-text"><a class="btn btn-md btn-success text-center" href="{% url 'edicion_producto' primero.id%}">Editar</a>
                        <p></p>
                        {%endif%} 
                        
                    </div>
                    </div> 
                </div>
    
                 {%endfor%}
                </div>
    
    <div class="card card-responsive" width="70%" style="padding:30px 30px 30px 30px">
        <h6 align="center">Más productos</h6>
        <ul class="list-group-xs" padding="20px 30px 20px 10px">
        
            {% for primero in ultimos_productos%}
            {%if not request.user.is_superuser%}
            <li class="list-group-item list-group-item-secondary"> 
                 <h8><a href="{% url 'mostrar_producto' primero.id%}">{{primero.titulo}} - {{primero.descripcion}}</a></h8>
            </li>
            {%else%}
            <li class="list-group-item list-group-item-secondary"> 
                <h8><a href="{% url 'edicion_producto' primero.id%}">{{primero.titulo}} - {{primero.descripcion}}</a></h8>
           </li>
            {%endif%}
            {%endfor%}
        </ul>
        </div>
  </div>
</div>

{%endblock%}

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Yaguarete S.A.</title>
         <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        <script src="{% static '/js/scripts.js' %}"></script>
    </head>
    <body>
        <div class="container">
        <header>
            <div id="cabecera">
             <img class="img-responsive" src="{% static '/media/yaguarete.jpg'%}" width="5%" heigth="5%">
             <div align="right">  
             {%if not request.user.is_authenticated %} 
                 
             <a class="btn btn-md btn-success" href="{% url 'login'%}?next={{request.path}}">Login</a>
             <a class="btn btn-md btn-success" href="{%  url 'USUARIOS:registrarse'%}">Registrarse</a>
             <a class="btn btn-md btn-success align-items-end" href="{%url 'carrito'%}">Carrito</a>
             {%else%}
              <h7>Bienvenido:</h7><h7 class="btn-danger">{{request.user}}</h7>
             {%if  not request.user.is_superuser%} 
             <a class="btn btn-md btn-success align-items-end" href="{%url 'carrito'%}">Carrito</a>
             {%endif%}
             <!--<a class="btn btn-md btn-success" href="{% url 'logout'%}?next={{request.path}}">Logout</a>-->
             <a class="btn btn-md btn-success" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
             {%endif%}

           </div>
        </header>       
         
        <nav class="navbar navbar-expand-sm navbar-light bg-light navbar-responsive" width="80%" id="mainNav">
                  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive">
                    Menu <i class="fa fa-bars"></i>
                  </button>
                  <div id="navbarResponsive" class="navbar-collapse collapse">
                    <if class="navbar-nav ml-auto text-uppercase">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'index'%}">HOME</a>
                      </li>
    
                      <li class="nav-item">
                        <div class="dropdown">
                            <a type="button" class="nav-link dropdown-toggle" data-toggle="dropdown">
                            Categorias
                            </a>
                            <div class="dropdown-menu">
                          
                                {% for categoria in lista_categorias %}
                               
                                   <a class="dropdown-item bg-light" href="{% url 'filtro_categoria' categoria.id%}">{{categoria.descripcion}}</a>
                                      
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                        
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'acerca'%}">ACERCA DE..</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'contacto'%}">CONTACTO</a>
                          </li>
                          {% if user.is_superuser%}
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'nuevo_producto'%}">NUEVO PRODUCTO</a>
                          </li>
                          {%endif%}
                          <li class="nav-item">
                               <input type="text" required="True" id="busca" value="" minlength="6" placeholder="termino a buscar">  
                                <a class="btn-sm bg-info  btn-info" onclick="window.location.href ='http://localhost:8000/buscar_producto/'+busca.value";>Buscar</a>
                               
                          </li>
                      </ul>
                  </div>
        
              </nav> 
              <div="container" height="80%" padding="30px 20px 20px 10px">
               <div class="shadow-lg">
                 <p></p>
                 <p></p>
                {% block content %}
                {% endblock %}
               </div>
              </div>
            

           <footer class="fixed-bottom">
                   
                <h6 class="bg-light" align="center">Yaguarete S.A. -Derechos Reservados ® 2021  - by Daniel Buzzi</h6> 
                  
           </footer>
        </div>
    </body>
</html>

TrabajoFinalBuzzi/TiendaYaguarete/Tienda/templates/tienda/mostrar_producto.html
{% extends "tienda/layout.html" %}

       
{% block content %}
{% if request.user.is_authenticated%}
{%if not request.user.is_superuser%}

<h4 class="text-center bg-success">{{producto_seleccionado.titulo}}</h4>
<div class="row" style="padding:15px 10px 40px 10px">
  <div class="col-6 text-center">
    <img class="text-center" src="{{producto_seleccionado.imagen.url}}"  width="250px" height="250px">
  </div> 
  <div  class="col border text-center">
<h5>{{categoria_seleccionada.descripcion}}</h5>
<p></p>
<h5 align="left"> {{producto_seleccionado.descripcion}}</h5>
<p></p>
<div  class="col text-center align-items-bottom" style="padding:50px 10px 80px 10px" >
  <h4>Precio $ {{producto_seleccionado.precio}}</h4>
  <a class="btn btn-xs btn-success" href="{% url 'agregar' producto_seleccionado.id%}">Agregar al carrito</a>
</div> 
</div>

   

     
 
</div>
{%else%}
 <he class="text-center">No tiene permiso de acceso para ver el producto</he>
{%endif%}

{%else%}
<h5 class="text-center">Precisa loguearse con permisos de usuario normal</h5>
{%endif%}
{% endblock %}